Exercício pandas 10/04

In [1]:
import pandas as pd

In [2]:
import os

In [4]:
os.listdir()

['aula0904.ipynb',
 'aula0904_2.ipynb',
 'aula1004.ipynb',
 'aula1004_2.ipynb',
 'aulas07e08_04.ipynb',
 'aula_pandas.ipynb',
 'data_variable_edit.csv',
 'estruturas1004.ipynb',
 'primeiro_note.ipynb']

In [15]:
df = pd.read_csv('data_variable_edit.csv')
df.head()

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0  Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated

In [16]:
df.tail()

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells Treatment
175  Sample 2      0.45     0.45    0.45     0.45   CD8      Mock
176  Sample 3      0.58     0.58    0.58     0.58   CD8      Mock
177  Sample 4      0.76     0.76    0.76     0.76   CD8      Mock
178  Sample 5      0.60     0.60    0.60     0.60   CD8      Mock
179  Sample 6      0.65     0.65    0.65     0.65   CD8      Mock

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sample     180 non-null    object
 1   DV1 BR90   180 non-null    float64
 2   DV2 265    180 non-null    float64
 3   DV3 98     180 non-null    float64
 4   DV4 360    180 non-null    float64
 5   Cells      180 non-null    object
 6   Treatment  180 non-null    object
dtypes: float64(4), object(3)
memory usage: 10.0+ KB

In [20]:
df.describe()

         DV1 BR90     DV2 265      DV3 98     DV4 360
count  180.000000  180.000000  180.000000  180.000000
mean     7.263833    7.413167    9.108333    6.624167
std     10.454712   10.944008   13.001236   10.534487
min      0.110000    0.110000    0.080000    0.010000
25%      1.387500    1.357500    1.067500    0.835000
50%      2.790000    2.595000    3.390000    1.970000
75%      6.900000    7.765000   12.047500    6.150000
max     52.380000   53.190000   81.420000   50.880000

In [19]:
df.select_dtypes(exclude='number').describe()

          Sample         Cells  Treatment
count        180           180        180
unique         6             6          5
top     Sample 1  CD4/CD8/CD19  Untreated
freq          30            30         36

In [21]:
len(df[df['Sample'] == 'Sample 1'])

30

In [22]:
df.query('Cells == "CD4/CD8/CD19"')

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0    Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1    Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2    Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3    Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4    Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated
5    Sample 6     50.16    53.19   50.76    46.78  CD4/CD8/CD19  Untreated
36   Sample 1     18.54    16.09   35.69    20.24  CD4/CD8/CD19       5 ug
37   Sample 2     18.45    18.82   25.13    18.12  CD4/CD8/CD19       5 ug
38   Sample 3     15.74    18.38   17.59    17.24  CD4/CD8/CD19       5 ug
39   Sample 4     18.78    18.80   26.13    15.90  CD4/CD8/CD19       5 ug
40   Sample 5     17.54    18.50   22.95    17.34  CD4/CD8/CD19       5 ug
41   Sample 6     17.62    18.79   22.22    17.09  CD4/CD8/CD19       5 ug
72   Sample 1      7.26     5.14   18.91     3.52  CD4/CD8/CD19      10 ug
73   Sample 2      7.26     5.14   18.91     3.52  CD4/CD8/CD19      10 ug
74   Sample 3      6.05     9.66    2.76     3.43  CD4/CD8/CD19      10 ug
75   Sample 4      7.28     7.29    9.35     1.91  CD4/CD8/CD19      10 ug
76   Sample 5      6.64     7.40    6.17     2.81  CD4/CD8/CD19      10 ug
77   Sample 6      6.78     8.23    6.08     2.85  CD4/CD8/CD19      10 ug
108  Sample 1      3.18     4.01    1.34     1.43  CD4/CD8/CD19      20 ug
109  Sample 2      2.90     2.85    6.05     1.98  CD4/CD8/CD19      20 ug
110  Sample 3      5.14     4.24    3.85     2.22  CD4/CD8/CD19      20 ug
111  Sample 4      3.73     3.70    3.75     1.87  CD4/CD8/CD19      20 ug
112  Sample 5      3.92     3.59    4.55     2.02  CD4/CD8/CD19      20 ug
113  Sample 6      4.26     3.84    4.04     2.04  CD4/CD8/CD19      20 ug
144  Sample 1      3.18     3.13    3.33     3.23  CD4/CD8/CD19       Mock
145  Sample 2      1.96     1.95    2.04     1.71  CD4/CD8/CD19       Mock
146  Sample 3      2.33     2.38    3.02     2.61  CD4/CD8/CD19       Mock
147  Sample 4      2.78     2.74    2.79     1.85  CD4/CD8/CD19       Mock
148  Sample 5      2.34     2.32    2.62     2.12  CD4/CD8/CD19       Mock
149  Sample 6      2.54     2.54    2.81     2.26  CD4/CD8/CD19       Mock

In [23]:
df.query('Cells == "CD4/CD8/CD19" and Sample == "Sample 1"')

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0    Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
36   Sample 1     18.54    16.09   35.69    20.24  CD4/CD8/CD19       5 ug
72   Sample 1      7.26     5.14   18.91     3.52  CD4/CD8/CD19      10 ug
108  Sample 1      3.18     4.01    1.34     1.43  CD4/CD8/CD19      20 ug
144  Sample 1      3.18     3.13    3.33     3.23  CD4/CD8/CD19       Mock

In [25]:
df[['Cells', 'Sample']]

            Cells    Sample
0    CD4/CD8/CD19  Sample 1
1    CD4/CD8/CD19  Sample 2
2    CD4/CD8/CD19  Sample 3
3    CD4/CD8/CD19  Sample 4
4    CD4/CD8/CD19  Sample 5
..            ...       ...
175           CD8  Sample 2
176           CD8  Sample 3
177           CD8  Sample 4
178           CD8  Sample 5
179           CD8  Sample 6

[180 rows x 2 columns]

In [27]:
df.loc[:,['Cells','Sample']]

            Cells    Sample
0    CD4/CD8/CD19  Sample 1
1    CD4/CD8/CD19  Sample 2
2    CD4/CD8/CD19  Sample 3
3    CD4/CD8/CD19  Sample 4
4    CD4/CD8/CD19  Sample 5
..            ...       ...
175           CD8  Sample 2
176           CD8  Sample 3
177           CD8  Sample 4
178           CD8  Sample 5
179           CD8  Sample 6

[180 rows x 2 columns]

In [30]:
df.loc[::-1].head()

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells Treatment
179  Sample 6      0.65     0.65    0.65     0.65   CD8      Mock
178  Sample 5      0.60     0.60    0.60     0.60   CD8      Mock
177  Sample 4      0.76     0.76    0.76     0.76   CD8      Mock
176  Sample 3      0.58     0.58    0.58     0.58   CD8      Mock
175  Sample 2      0.45     0.45    0.45     0.45   CD8      Mock

In [31]:
df.columns

Index(['Sample', 'DV1 BR90', 'DV2 265', 'DV3 98', 'DV4 360', 'Cells',
       'Treatment'],
      dtype='object')

In [35]:
df[df[df.columns[-2]].isin(['CD4/CD8/CD19', 'CD4/CD8'])].head()

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0  Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated

In [36]:
df[~df[df.columns[-2]].isin(['CD4/CD8/CD19', 'CD4/CD8'])].head()

      Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells  Treatment
12  Sample 1      4.23     4.10   17.12     6.18  CD14  Untreated
13  Sample 2      5.58     4.12   12.19     3.13  CD14  Untreated
14  Sample 3      3.31     2.68    7.70     2.59  CD14  Untreated
15  Sample 4      5.54     4.39   12.34     6.66  CD14  Untreated
16  Sample 5      4.67     3.82   10.74     4.64  CD14  Untreated

In [37]:
df.value_counts()

Sample    DV1 BR90  DV2 265  DV3 98  DV4 360  Cells         Treatment
Sample 1  0.52      0.76     0.08    0.13     CD8           20 ug        1
          0.80      0.80     0.80    0.80     CD4           Mock         1
          0.92      0.89     1.49    1.34     CD14          Mock         1
          1.19      1.14     1.38    1.27     CD19          Mock         1
          1.23      0.48     0.17    0.03     CD4           10 ug        1
                                                                        ..
Sample 6  17.62     18.79    22.22   17.09    CD4/CD8/CD19  5 ug         1
          21.78     21.45    16.03   16.96    CD19          Untreated    1
          22.44     25.04    27.88   24.45    CD8           Untreated    1
          27.19     30.55    33.96   28.91    CD4/CD8       Untreated    1
          50.16     53.19    50.76   46.78    CD4/CD8/CD19  Untreated    1
Name: count, Length: 180, dtype: int64

In [38]:
df.value_counts('Cells')

Cells
CD14            30
CD19            30
CD4             30
CD4/CD8         30
CD4/CD8/CD19    30
CD8             30
Name: count, dtype: int64

In [40]:
df.sort_index(ascending=False).head()

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells Treatment
179  Sample 6      0.65     0.65    0.65     0.65   CD8      Mock
178  Sample 5      0.60     0.60    0.60     0.60   CD8      Mock
177  Sample 4      0.76     0.76    0.76     0.76   CD8      Mock
176  Sample 3      0.58     0.58    0.58     0.58   CD8      Mock
175  Sample 2      0.45     0.45    0.45     0.45   CD8      Mock

In [41]:
df.sort_values(by='Cells').value_counts('Cells')

Cells
CD14            30
CD19            30
CD4             30
CD4/CD8         30
CD4/CD8/CD19    30
CD8             30
Name: count, dtype: int64

In [42]:
df[[df.columns[0],df.columns[1]]].nlargest(5, columns=df.columns[1])

     Sample  DV1 BR90
3  Sample 4     52.38
1  Sample 2     52.17
5  Sample 6     50.16
4  Sample 5     49.51
2  Sample 3     45.37

In [44]:
df[[df.columns[1]]].nlargest(5, columns=df.columns[1])

   DV1 BR90
3     52.38
1     52.17
5     50.16
4     49.51
2     45.37

In [43]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,170,171,172,173,174,175,176,177,178,179
Sample,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,...,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6
DV1 BR90,44.54,52.17,45.37,52.38,49.51,50.16,23.44,25.76,29.13,25.75,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV2 265,39.56,52.71,52.28,52.49,51.85,53.19,19.5,26.92,35.21,26.92,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV3 98,81.42,52.13,42.48,58.69,51.1,50.76,27.48,32.45,36.23,32.06,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV4 360,48.23,49.19,50.88,38.85,47.4,46.78,25.89,27.97,29.84,28.35,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
Cells,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8,CD4/CD8,CD4/CD8,CD4/CD8,...,CD4,CD4,CD4,CD4,CD8,CD8,CD8,CD8,CD8,CD8
Treatment,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,...,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock

In [47]:
df['Treatment'].value_counts()

Treatment
Untreated    36
5 ug         36
10 ug        36
20 ug        36
Mock         36
Name: count, dtype: int64

In [51]:
pd.get_dummies(df['Treatment']).head()

   10 ug  20 ug   5 ug   Mock  Untreated
0  False  False  False  False       True
1  False  False  False  False       True
2  False  False  False  False       True
3  False  False  False  False       True
4  False  False  False  False       True

In [52]:
df.value_counts()

Sample    DV1 BR90  DV2 265  DV3 98  DV4 360  Cells         Treatment
Sample 1  0.52      0.76     0.08    0.13     CD8           20 ug        1
          0.80      0.80     0.80    0.80     CD4           Mock         1
          0.92      0.89     1.49    1.34     CD14          Mock         1
          1.19      1.14     1.38    1.27     CD19          Mock         1
          1.23      0.48     0.17    0.03     CD4           10 ug        1
                                                                        ..
Sample 6  17.62     18.79    22.22   17.09    CD4/CD8/CD19  5 ug         1
          21.78     21.45    16.03   16.96    CD19          Untreated    1
          22.44     25.04    27.88   24.45    CD8           Untreated    1
          27.19     30.55    33.96   28.91    CD4/CD8       Untreated    1
          50.16     53.19    50.76   46.78    CD4/CD8/CD19  Untreated    1
Name: count, Length: 180, dtype: int64

In [54]:
df.value_counts().to_frame()

                                                                 count
Sample   DV1 BR90 DV2 265 DV3 98 DV4 360 Cells        Treatment
Sample 1 0.52     0.76    0.08   0.13    CD8          20 ug          1
         0.80     0.80    0.80   0.80    CD4          Mock           1
         0.92     0.89    1.49   1.34    CD14         Mock           1
         1.19     1.14    1.38   1.27    CD19         Mock           1
         1.23     0.48    0.17   0.03    CD4          10 ug          1
...                                                                ...
Sample 6 17.62    18.79   22.22  17.09   CD4/CD8/CD19 5 ug           1
         21.78    21.45   16.03  16.96   CD19         Untreated      1
         22.44    25.04   27.88  24.45   CD8          Untreated      1
         27.19    30.55   33.96  28.91   CD4/CD8      Untreated      1
         50.16    53.19   50.76  46.78   CD4/CD8/CD19 Untreated      1

[180 rows x 1 columns]

In [60]:
coluna1 = df.columns[0]
coluna2 = df.columns[-1]
print(coluna1,coluna2)
display(
    df.value_counts([
        coluna1,
        coluna2
    ])
    .to_frame()
    .rename(columns={0: 'Freq Abso Simp'})
    .sort_index()
)

Sample Treatment

                    count
Sample   Treatment
Sample 1 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 2 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 3 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 4 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 5 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 6 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6

In [61]:
df.groupby('Cells').sum()

,Sample,DV1 BR90,DV2 265,DV3 98,DV4 360,Treatment
Cells,,,,,,
CD14,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,64.31,54.24,150.46,64.45,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD19,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,192.37,188.63,278.12,160.54,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,76.95,73.17,79.47,58.43,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4/CD8,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,277.77,292.89,300.59,261.84,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4/CD8/CD19,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,480.33,491.61,588.66,430.64,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD8,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,215.76,233.83,242.20,216.45,UntreatedUntreatedUntreatedUntreatedUntreatedU...

In [63]:
colunas = [1,2,3,4,5]
(
df.iloc[:, colunas]
.groupby("Cells")
.sum()
)

              DV1 BR90  DV2 265  DV3 98  DV4 360
Cells
CD14             64.31    54.24  150.46    64.45
CD19            192.37   188.63  278.12   160.54
CD4              76.95    73.17   79.47    58.43
CD4/CD8         277.77   292.89  300.59   261.84
CD4/CD8/CD19    480.33   491.61  588.66   430.64
CD8             215.76   233.83  242.20   216.45

In [65]:
colunas = [1,2,3,4,5,6]
(
df.iloc[:, colunas]
.groupby(["Cells","Treatment"])
.sum()
)

                        DV1 BR90  DV2 265  DV3 98  DV4 360
Cells        Treatment
CD14         10 ug          8.52     7.26   22.61     9.72
             20 ug          8.50     8.50   15.94     8.50
             5 ug          13.09    10.66   33.06    12.80
             Mock           6.10     4.96    8.50     5.97
             Untreated     28.10    22.86   70.35    27.46
CD19         10 ug         14.95    14.60   59.73    12.94
             20 ug          9.35     9.35   17.40     9.35
             5 ug          31.49    30.85   57.50    25.90
             Mock           7.69     7.54    9.35     6.33
             Untreated    128.89   126.29  134.14   106.02
CD4          10 ug          7.91     7.64    1.59     0.67
             20 ug          9.60     8.74    4.43     1.24
             5 ug          17.64    16.22   22.21    16.88
             Mock           3.59     3.59    3.59     3.59
             Untreated     38.21    36.98   47.65    36.05
CD4/CD8      10 ug         25.58    27.53    2.66     4.52
             20 ug         13.38    12.48    5.93     1.83
             5 ug          73.54    76.90   89.38    78.73
             Mock           7.08     7.16    6.86     7.18
             Untreated    158.19   168.82  195.76   169.58
CD4/CD8/CD19 10 ug         41.27    42.86   62.18    18.04
             20 ug         23.13    22.23   23.58    11.56
             5 ug         106.67   109.38  149.71   105.93
             Mock          15.13    15.06   16.61    13.78
             Untreated    294.13   302.08  336.58   281.33
CD8          10 ug         19.04    21.16    2.53     5.16
             20 ug          4.81     4.77    2.93     1.60
             5 ug          58.50    63.09   72.44    64.10
             Mock           4.30     4.30    4.30     4.30
             Untreated    129.11   140.51  160.00   141.29

In [68]:
colunas = [1,2,3,4,5,6]
(
df.iloc[:, colunas]
.groupby(["Cells","Treatment"])
.mean()
.round(2)
)

                        DV1 BR90  DV2 265  DV3 98  DV4 360
Cells        Treatment
CD14         10 ug          1.42     1.21    3.77     1.62
             20 ug          1.42     1.42    2.66     1.42
             5 ug           2.18     1.78    5.51     2.13
             Mock           1.02     0.83    1.42     1.00
             Untreated      4.68     3.81   11.72     4.58
CD19         10 ug          2.49     2.43    9.96     2.16
             20 ug          1.56     1.56    2.90     1.56
             5 ug           5.25     5.14    9.58     4.32
             Mock           1.28     1.26    1.56     1.06
             Untreated     21.48    21.05   22.36    17.67
CD4          10 ug          1.32     1.27    0.26     0.11
             20 ug          1.60     1.46    0.74     0.21
             5 ug           2.94     2.70    3.70     2.81
             Mock           0.60     0.60    0.60     0.60
             Untreated      6.37     6.16    7.94     6.01
CD4/CD8      10 ug          4.26     4.59    0.44     0.75
             20 ug          2.23     2.08    0.99     0.30
             5 ug          12.26    12.82   14.90    13.12
             Mock           1.18     1.19    1.14     1.20
             Untreated     26.36    28.14   32.63    28.26
CD4/CD8/CD19 10 ug          6.88     7.14   10.36     3.01
             20 ug          3.86     3.70    3.93     1.93
             5 ug          17.78    18.23   24.95    17.65
             Mock           2.52     2.51    2.77     2.30
             Untreated     49.02    50.35   56.10    46.89
CD8          10 ug          3.17     3.53    0.42     0.86
             20 ug          0.80     0.80    0.49     0.27
             5 ug           9.75    10.52   12.07    10.68
             Mock           0.72     0.72    0.72     0.72
             Untreated     21.52    23.42   26.67    23.55

In [69]:
pd.crosstab(df['Cells'], df['Treatment'], margins=True)

Treatment     10 ug  20 ug  5 ug  Mock  Untreated  All
Cells
CD14              6      6     6     6          6   30
CD19              6      6     6     6          6   30
CD4               6      6     6     6          6   30
CD4/CD8           6      6     6     6          6   30
CD4/CD8/CD19      6      6     6     6          6   30
CD8               6      6     6     6          6   30
All              36     36    36    36         36  180

In [70]:
df.pivot_table(
    index='Cells',
    columns='Treatment',
    values='DV1 BR90',
    aggfunc='mean'
)

Treatment        10 ug     20 ug       5 ug      Mock  Untreated
Cells
CD14          1.420000  1.416667   2.181667  1.016667   4.683333
CD19          2.491667  1.558333   5.248333  1.281667  21.481667
CD4           1.318333  1.600000   2.940000  0.598333   6.368333
CD4/CD8       4.263333  2.230000  12.256667  1.180000  26.365000
CD4/CD8/CD19  6.878333  3.855000  17.778333  2.521667  49.021667
CD8           3.173333  0.801667   9.750000  0.716667  21.518333

In [71]:
df.pivot_table(
    index='Cells',
    columns='Treatment',
    values='DV1 BR90',
    aggfunc='median'
)

Treatment     10 ug  20 ug    5 ug   Mock  Untreated
Cells
CD14          1.420  1.430   2.200  1.025      4.720
CD19          2.500  1.580   5.275  1.290     21.600
CD4           1.345  1.575   2.855  0.635      6.360
CD4/CD8       4.090  2.195  12.030  1.190     26.340
CD4/CD8/CD19  7.020  3.825  18.035  2.440     49.835
CD8           2.970  0.790   9.685  0.625     21.630

In [76]:
(
df['DV4 360']
.to_frame()
.sort_values(by='DV4 360', ascending=False)
.head(10)
.style
.text_gradient(cmap='Blues')
)

In [75]:
import jinja2

In [77]:
df["DV1 BR90"] == df['DV1 BR90'].max()

0      False
1      False
2      False
3       True
4      False
       ...
175    False
176    False
177    False
178    False
179    False
Name: DV1 BR90, Length: 180, dtype: bool

In [ ]:
def highlight_max(s):
    is_max = s == s.max()
return

SyntaxError: invalid syntax (2283075969.py, line 2)