Operadores aritmeticos

In [ ]:
# soma e subtração
num_1 = 4
num_2 = 2
print(num_1+num_2)
print(num_1-num_2)

6
2

In [62]:
# objetos compostos
tupla1 = (1, 2, 3, 4)
tupla2 = (1, 2, 3, 4)

print(tupla1+tupla2)

(1, 2, 3, 4, 1, 2, 3, 4)

In [63]:
#soma uma tupla com ela mesma
tupla1 += tupla2
display(tupla1)
display(tupla2)

(1, 2, 3, 4, 1, 2, 3, 4)

(1, 2, 3, 4)

In [64]:
# transforma tupla em lista
listatupla = list(tupla1)
listatupla

[1, 2, 3, 4, 1, 2, 3, 4]

In [65]:
#cada vez que da play, faz uma soma (em tupla não da, só na lista)
listatupla[2] += 2
listatupla

[1, 2, 5, 4, 1, 2, 3, 4]

In [66]:
dict1 = {"a": 1, "b": 2, "c": 3, "d": 4}
dict2 = {"aa": 1, "bb": 2, "cc": 3, "dd": 4}
print(dict1, dict2)

{'a': 1, 'b': 2, 'c': 3, 'd': 4} {'aa': 1, 'bb': 2, 'cc': 3, 'dd': 4}

In [67]:
dict1.update(dict2)
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'aa': 1, 'bb': 2, 'cc': 3, 'dd': 4}

In [55]:
import numpy as np

In [68]:
array = np.array(listatupla)
array

array([1, 2, 5, 4, 1, 2, 3, 4])

In [69]:
array += 2
array

array([3, 4, 7, 6, 3, 4, 5, 6])

In [70]:
array *= array
array

array([ 9, 16, 49, 36,  9, 16, 25, 36])

In [71]:
np.insert(arr=array, obj=2, values=100)

array([  9,  16, 100,  49,  36,   9,  16,  25,  36])

In [74]:
array = np.array(listatupla).reshape(4,2)

In [75]:
array

array([[1, 2],
       [5, 4],
       [1, 2],
       [3, 4]])

In [77]:
df = np.array
array

array([[1, 2],
       [5, 4],
       [1, 2],
       [3, 4]])

Operadores relacionais vao voltar em booleano

In [79]:
"P" == "y"

False

In [80]:
0.0 == False

True

In [81]:
"0.0" == False

False

In [82]:
2 >= 2.01

False

In [83]:
2 <= 3 < 4

True

In [85]:
import pandas as pd

In [86]:
(1, 2) == (1.0 , 2.0)

True

In [87]:
(1, 2) == [1, 2]

False

In [88]:
(1, 2) == (1.0, 2.0, 1)

False

In [ ]:
{"a": 1} == {"a": 1.0}

True

In [90]:
lista1 = [1, 2]
lista2 = [1, 2]
lista1 == lista2

True

In [91]:
{"a": 1}.keys() == {"a": 1}.keys()

True

In [94]:
{"a": 1}.items() <= {"a": 1}.items()

True

In [95]:
{"a": 1}.values() == {"a": 1}.values()

False

In [96]:
{"a": 1}.values() >= {"a": 1}.values()

TypeError: '>=' not supported between instances of 'dict_values' and 'dict_values'

In [102]:
'a' <= 'b'

True

In [101]:
'a' == 'b'

False

In [103]:
'c' == 'C'

False

In [107]:
np.random.normal(0, 1, 100)

array([-0.89804595,  0.46316148, -0.77887235,  0.71203956,  0.6664827 ,
       -0.48127585,  0.27821599, -0.06211007,  1.20984569,  0.1507772 ,
        1.48945674, -1.05064182, -1.15396833,  2.04736571,  0.34028559,
        0.89902366,  0.4646336 ,  0.69033627, -0.13809014,  1.83057745,
       -0.57078317,  0.98566781,  0.98588663, -1.74480866,  2.3944292 ,
        1.02611123, -0.05639967, -0.5860784 ,  1.03818885,  0.57476279,
        0.03813826, -1.8857187 ,  0.59291166,  0.06557439,  1.06589081,
       -1.2672778 , -0.74429512, -1.62120791, -0.36344523,  0.3727672 ,
        0.25634056, -0.38284624,  1.16826245, -0.83386275,  1.10428803,
        0.25805631,  0.52002042, -0.08022014, -0.35883191,  0.81229461,
       -0.67549812,  2.66520757,  0.67170384,  2.29251711,  0.66511199,
       -0.79324335, -2.1371156 ,  0.71712535, -0.8896083 , -0.10883394,
       -0.11538402, -0.34288209, -0.15764226, -0.39138707, -0.36306231,
        0.16086291,  1.01553861, -0.35501642,  0.18697767, -0.38819711,
       -2.19609644,  1.93912554, -0.27103849,  1.05546283, -1.37715836,
        0.30344158, -0.34576976,  1.26186813,  3.22856415,  0.28394418,
        0.1538749 , -0.09651742,  1.03595259,  0.8532462 , -0.79584608,
        0.01890851,  0.36143358, -0.8336518 ,  0.85623903,  0.01755844,
       -0.54151216,  1.24620966,  0.71568009, -1.28271608, -0.65657973,
       -1.2458665 , -0.19411008,  0.59238726,  0.38349008, -0.19568941])

In [116]:
np.random.seed(42)
array1 = np.random.normal(0, 1, 100).reshape(-1, 10)
array2 = np.random.normal(0, 1, 100).reshape(-1, 10)
array1[:2]

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
        -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [118]:
array1 == array2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [117]:
np.random.seed(42)
array1 = np.random.normal(0, 1, 100).reshape(-1, 10)
array2 = np.random.normal(0, 1, 100).reshape(-1, 10)
print(array1[:1])
print(array2[:1])

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
   1.57921282  0.76743473 -0.46947439  0.54256004]]
[[-1.41537074 -0.42064532 -0.34271452 -0.80227727 -0.16128571  0.40405086
   1.8861859   0.17457781  0.25755039 -0.07444592]]

In [120]:
pd.DataFrame(array1) <= pd.DataFrame(array2)

       0      1      2      3      4      5      6      7      8      9
0  False  False  False  False   True   True   True  False   True  False
1  False   True  False   True   True   True   True  False   True   True
2  False  False   True   True   True   True   True  False   True  False
3  False  False  False   True  False   True  False   True   True  False
4  False   True  False   True   True   True  False  False   True   True
5  False   True  False  False  False  False   True   True  False  False
6  False   True   True   True   True  False   True   True  False  False
7  False  False  False  False   True   True  False   True  False   True
8   True  False  False   True   True   True  False  False  False  False
9  False  False   True  False   True   True  False  False   True  False

In [122]:
filtro_array = array1 <= array2
filtro_array[:2]

array([[False, False, False, False,  True,  True,  True, False,  True,
        False],
       [False,  True, False,  True,  True,  True,  True, False,  True,
         True]])

In [123]:
df1 = pd.DataFrame(array1)
df2 = pd.DataFrame(array2)
df1.head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040

In [124]:
df1[filtro_array].head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.91328,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304